version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: 'root'
      POSTGRES_USER: 'nestjs-template'
      POSTGRES_PASSWORD: 'root'
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .env.docker:/.env
volumes:
  db: