name: Integration Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.7.0
      - name: Npm install
        run: npm i
      - name: Build test
        run: npm run build
      - name: Unit test service
        run: npm run test
      - name: Integrate
        run: |
          npm run lint
          npm run format